import Provider from "@/app/provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const runtime = "edge";

const LiAlinurImratANSI = localFont({
  src: "./fonts/LiAlinurImaratANSI.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LiAlinurImratANSI.variable} bg-black `}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
